### ISSUE TITLE
Handle typescript throwing errors on build gracefully

### ISSUE THREAD

**Issue by seawatts** [denali-js/denali-typescript#9]
I believe this is causing the whole build to fail when it throws an exception for type errors.

Maybe try catch around here? 

https://github.com/denali-js/denali-typescript/blob/e1d4bcfe48eeb9cc494fed73ec4e840368a55e8f/denali-build.js#L18-L25

Update:

Looks like you can pass in `throwOnError` param

https://github.com/tildeio/broccoli-typescript-compiler/blob/8c056cbe417757b60380b51619a876cc5e0ae90b/lib/diagnostics-handler.ts#L10

Which gets passed in here:

https://github.com/tildeio/broccoli-typescript-compiler/blob/master/lib/plugin.ts#L47

Ah ha: Looks like in `NODE_ENV = 'production'` it will throw

https://github.com/tildeio/broccoli-typescript-compiler/blob/master/lib/normalize-options.ts#L30

**Comment by seawatts** [comment]
On that note. Should we be setting `NODE_ENV = 'production'` during a `denali publish`? So that we don't publish broken types?

https://github.com/denali-js/denali/blob/master/commands/publish.ts#L54

**Comment by davewasmer** [comment]
> Maybe try catch around here?

Just a quick protip on Broccoli - when you create Broccoli trees, a la `new Funnel('foo')`, that's really more of a "design" step. The build doesn't happen on that line - rather, you a designing a dependency graph of sorts, saying "this tree connects to this tree" and so on. Then, at the end, when you call `builder.build(lastAndFinalMergedTree)`, Broccoli actually works backwards through that dependency graph you built up, and kicks off the build (in order) _then_.

So wrapping that line with a try/catch wouldn't help, because that line just says "then we'll take the output and compile it into Typescript", it doesn't actually do the compilation.

That nuance was one of the bigger mental hurdles for me in grokking Broccoli, but it's super nice, because it allows us to compose these build trees together in a really elegant way.

> Looks like you can pass in throwOnError param

If we don't `throwOnError`, does TS still produce any output? If not, that would be problematic if you have subsequent build steps expecting JS to be there.

> On that note. Should we be setting NODE_ENV = 'production' during a denali publish? So that we don't publish broken types?

Yea, probably.

**Comment by davewasmer** [comment]
Closing as stale.

I'm unable to reproduce this issue, and given the lack of activity, I'm guessing it has since been fixed elsewhere.

Of course - if you are still impacted by this bug, feel free to leave a comment (ideally with a reproduction) and I'll reopen the issue.

**Comment by davewasmer** [comment]
Btw, filed denali-js/denali-cli#35 for making sure addons use `--environment production` during their publish step
